excalibur:
  type: [Weapon]
  description: "Ye sword of olde"
  use:
      text: "You slash with the sword."
      action: "interact"
  min-damage: 1
  max-damage: 10
poison frog:
  type: [Weapon, Animal]
  description: "A bright purple frog, oozing a thick liquid"
  use:
      text: "You place the frog gently on the floor. The frog croaks contentedly."
      action: "drop"
  min-damage: 2
  max-damage: 4
broom:
  type: [Item]
  description: "It's for sweeping."
  use:
      text: "The floor looks slightly less dusty."
      action: "interact"
bucket:
  type: [Item]
  description: "It's empty."
  use:
      text: "You put the bucket on your head. You feel marginally safer."
      action: "interact"
mop:
  type: [Item]
  description: "It's for mopping."
  use:
      text: "The floor looks slightly more damp."
      action: "interact"
poster:
  type: [Item]
  description: "A classic."
  use:
      text: "What are you going to do with a poster?"
      action: "interact"
book:
  type: [Item]
  description: "An old book about Java. It seems to have some purple residue on it."
  use:
      text: "You place the book gently on the floor."
      action: "drop"
plant:
  type: [Item, Plant]  
  description: "A small dying plant."
  use:
      text: "You water the plant."
      action: "water"
bookshelf:
  type: [Item]
  description: "A dusty bookshelf."
  use:
     text: "You look at the bookcase, one seems to be missing."
     action: "interact"
TV:
  type: [Item]
  description: "A old rusty television. The screen is off."
  use:
      text: "You press the power button. Nothing happens."
      action: "interact"
rug:
  type: [Item]
  description: "An old, dusty rug with a faded pattern."
  use:
      text: "You check under the rug. Nothing is there"
      action: "interact"
key:
  type: [Item, Key]  
  description: "A rusty key"
  use:
      text: "You insert the key into the hole. One click to the left and the door swings open."
      action: "unlock"
