excalibur:
  type: [Weapon]
  description: "Ye sword of olde"
  use:
      text: "You slash with the sword."
      action: "null"
  min-damage: 1
  max-damage: 10
poison frog:
  type: [Weapon, Animal]
  description: "A bright purple frog, oozing a thick liquid"
  use:
      text: "You place the frog gently on the floor. The frog croaks contentedly."
      action: "drop"
  min-damage: 2
  max-damage: 4
broom:
  type: [Item]
  description: "It's for sweeping."
  use:
      text: "The floor looks slightly less dusty."
      action: "null"
bucket:
  type: [Item]
  description: "It's empty."
  use:
      text: "You put the bucket on your head. You feel marginally safer."
      action: "null"
mop:
  type: [Item]
  description: "It's for mopping."
  use:
      text: "The floor looks slightly more damp."
      action: "null"
poster:
  type: [Item]
  description: "A classic."
  use:
      text: "What are you going to do with a poster?"
      action: "null"
book:
  type: [Item]
  description: "An old book about Java. It seems to have some purple residue on it."
  use:
      text: "You place the book gently on the floor."
      action: "drop"
# new Item Mug
mug:
  type: [Item]
  description: "A very basic white mug with a letter T on it.  It seems to contain a mysterious unknown liquid"
  use:
    text: "You drink the mug."
    action: "drink"
# new item table
table:
  type: [Item]
  description: "An old rustic long wooden table"
  use:
    text: "This table is to heavy to move"
    action: "null"
# new item chair
chair:
  type: [Item]
  description: "It looks like 10 sticks were strung together"
  use:
    text: "The chair is not very comfortable"
    action: "sit"
# new item key
rustic bronze key:
  type: [Key, Item]
  description: "An old, rustic key that doesn't seem special at all."
  use:
    text: "This key might be useful to unlock a door"
    action: "unlock"
# Sword
gilded 2h sword:
  type: [Weapon, Item]
  description: "This is a shiny gold sword that looks very rare."
  use:
    text: "This sword looks important"
    action: "null"


