excalibur:
  type: [Weapon]
  description: "Ye sword of olde"
  use:
      text: "You slash with the sword."
      action: "null"
  min-damage: 1
  max-damage: 10
poison frog:
  type: [Weapon, Animal]
  description: "A bright purple frog, oozing a thick liquid"
  use:
      text: "You place the frog gently on the floor. The frog croaks contentedly."
      action: "drop"
  min-damage: 2
  max-damage: 4
crowbar:
  type: [Item]
  description: "This could be useful."
  use:
      text: "Test"
      action: "null"
bucket:
  type: [Item]
  description: "It's empty."
  use:
      text: "You put the bucket on your head. You feel marginally safer."
      action: "null"
mop:
  type: [Item]
  description: "It's for mopping."
  use:
      text: "The floor looks slightly more damp."
      action: "null"
poster:
  type: [Item]
  description: "A classic."
  use:
      text: "What are you going to do with a poster?"
      action: "null"
book:
  type: [Item]
  description: "A dusty old book titled \"A final proof of the Riemann Hypothesis\""
  use:
      text: "Who even likes math anyways."
      action: "drop"
