excalibur:
  type: [Weapon]
  description: "Ye sword of olde"
  use:
      text: "You slash with the sword."
      action: "null"
  min-damage: 1
  max-damage: 10
poison frog:
  type: [Weapon, Animal]
  description: "A bright purple frog, oozing a thick liquid"
  use:
      text: "You place the frog gently on the floor. The frog croaks contentedly."
      action: "drop"
  min-damage: 2
  max-damage: 4
broom:
  type: [Item]
  description: "It's for sweeping."
  use:
      text: "The floor looks slightly less dusty."
      action: "null"
bucket:
  type: [Item]
  description: "It's empty."
  use:
      text: "You put the bucket on your head. You feel marginally safer."
      action: "null"
mop:
  type: [Item]
  description: "It's for mopping."
  use:
      text: "The floor looks slightly more damp."
      action: "null"
poster:
  type: [Item]
  description: "A classic."
  use:
      text: "What are you going to do with a poster?"
      action: "null"
book:
  type: [Item]
  description: "An old book about Java. It seems to have some purple residue on it."
  use:
      text: "You place the book gently on the floor."
      action: "drop"
crystal ball:
  type: [Magic, Weapon]
  description: "Energy from the Arcane seems to resonate within"
  effect: "cast fireball"
  use:
      text: "The ball starts to float, seemingly fills you with energy and knowledge of the Arcane... you suddenly feel the ability to cast fire ball"
      action: "null"
  min-damage: 10
  max-damage: 20
shield:
  type: [Item, Weapon]
  description: "Solid yet durable, has a insignia unknown to you"
  use:
      text: "Its a solid piece of metal, you feel reassured it can protect you, yet you wonder why you feel the need to protect yourself..."
      action: "null"
  min-damage: 5
  max-damage: 15
map:
  type: [Item]
  description: "Resembles and old pirate map, almost like it leads to another room..."
  use:
      text: "You pick up the map and it shows all the rooms, there is a specific room with a weird symbol on it, but beyond that it seems there is a door to the outside..."
      action: "null"
rat:
  type: [Animal]
  description: "Its furry and grey, thats it."
  use:
      action: "null"
  min-damage: 1 
  max-damage: 2
dagger:
  type: [Item, Weapon]
  description: "Small and sharp, it feels almost weightless in your hands... it could help defend yourself"
  use:
      text: "You examine the blade, it feels oddly sharp, for what it looks like... you feel like you could so some damage with this"
      action: "null"
  min-damage: 1
  max-damage: 5
carnivorous plant:
  type: [Animal]
  description: "It seems to resemble the piranha plant from the hit Mario games... except its real."
  use:
      action: "null"
  min-damage: 5
  max-damage: 15
medicinal herbs:
  type: [Item]
  description: "The leaves look soft, giving you a almost calming feel, like you would feel a lot better if you ate them..."
  use:
      text: "You feel replenished, all of your injuries have healed, and you feel like you can take on the world"
      action: "null"
mysterious seeds:
  type: [Item]
  description: "They resemble smaller cocoa fruits, the smell oddly sweet, but the fact that they came from a murderous monster puts you off"
  use:
      action: "null"
brown key:
  type: [Item]
  description: "Seems to be an old wooden brown key, yet the brown feels unnaturally brown... almost like paint"
  use:
    action: "null"
enchanted scroll:
  type: [Magic]
  description: "An ancient scroll with cryptic runes"
  effect: "gain knowledge"
  use:
    text: "You read the scroll and feel that your magic arcana has expanded"
    action: "null"
mystic cloak:
  type: [Magic]
  description: "A cloak that shimmers in the dark, it looks like its owner took good care of it"
  effect: "invisibility"
  use:
    text: "The cloak envelops you, and it fits well, so well you don't notice you've become invisible"
    action: "null"
  