hammer:
  type: [Weapon]
  description: "A rusty old hammer"
  use:
      text: "You swing the hammer over your head"
      action: "Attack"
  min-damage: 1
  max-damage: 10
glowing slug:
  type: [Animal]
  description: "A bright purple frog, oozing a thick liquid"
  use:
      text: "You place the frog gently on the floor. The frog croaks contentedly."
      action: "Attack"
  min-damage: 0
  max-damage: 1
crowbar:
  type: [Key]
  description: "This could be useful."
  use:
      text: "You use the crowbar to pry open the yellow door, you hear a creaking sound in the distance..."
      action: "Unlock"
plant:
  type: [Plant]
  description: "A small plant"
  use:
      text: "A small potted plant, it makes you happy."
      action: "Inspect"
healing:
  type: [Healing]
  description: "A bandage soaked in  floral liquid"
  use:
      text: "You wrap your wounds with the bandage, you feel better!"
      action: "Heal"
poster:
  type: [Item]
  description: "A classic."
  use:
      text: "What are you going to do with a poster?"
      action: "null"
book:
  type: [Item]
  description: "A dusty old book titled \"A final proof of the Riemann Hypothesis\""
  use:
      text: "Who even likes math anyways."
      action: "drop"
