scorpion:
  type: [Animal]
  description: "A venomous scorpion, its tail arched and ready to strike."
  use:
      text: "The scorpion arches its tail as you get closer. You shouldn't touch it."
      action: "inspect"
  touch:
      text: "You reach out to touch the scorpion, and it stings you! You feel a burning pain as the venom takes hold..."
      action: "end_game"

sand:
  type: [Item]
  description: "A million golden pieces of sand, with thousands more slipping through your fingers."
  use:
      text: "You throw the sand. It gets in your eyes... useful..."
      
lighter:
  type: [Item]
  description: "A small metal lighter, low on fuel but still functional."
  use:
      text: "The lighter flickers to life, its flame small but steady."
      action: "ignite"

coconut tree:
  type: [Item]
  description: "A tall tree bearing coconuts that sway gently in the breeze."
  use:
      text: "You try to shake the tree, but nothing falls."
      action: "null"

spring:
  type: [Item]
  description: "A bubbling natural spring with cool, clear water."
  use:
      text: "You take a sip from the spring and feel refreshed."
      action: "heal"

statue:
  type: [Item]
  description: "A weathered stone statue with an unreadable inscription."
  use:
      text: "The statue's eyes glow faintly as the brazier is lit, and a deep voice resonates: 'Who dares come before me?'"
      action: "speak"

unlit brazier:
  type: [Stationary]
  description: "A large metal brazier, filled with ash but unlit."
  use:
      text: "The lighter flickers, but the brazier remains unlit. 'This won't work,' you mutter to yourself."
      action: "null"

hidden symbols:
  type: [Item]
  description: "Mysterious symbols carved into the cavern walls, glowing faintly."
  use:
      text: "You trace the symbols with your fingers, and they briefly shine brighter."
      action: "inspect"

unlit torch:
  type: [Item]
  description: "A wooden torch, unlit but ready to be used."
  use:
      text: "You light the torch with the lighter. The flames burst forth, illuminating your surroundings."
      action: "light"

minecart:
  type: [Item]
  description: "An old, rusty minecart. It looks like it hasn't been used in years."
  use:
      text: "You push the minecart, and it screeches along the tracks."
      action: "push"

ancient scroll:
  type: [Item]
  description: "A fragile parchment with ancient text."
  use:
      text: "You attempt to decipher the text."
      action: "read"

treasure chest:
  type: [Item]
  description: "A locked chest, potentially filled with treasures."
  use:
      text: "You try to open the chest, but it remains locked."
      action: "null"
