Old Book:
  type: Book
  description: "An old book, falling apart at the seams. Bookworms have had their way with this one."
  use:
    text: "You read the book, and remember the most important parts."
    action: "read"
  tip: "The Warden seeks an animal, a plant, and some delicious food."

Library Key:
  type: Key
  description: "A rather antique key. The lock this goes to must be easy to pick."
  use:
    text: "With a loud ker-CHUNK, the door to the library is now open"
    action: "unlock"
  room: "Library"
  useRoom: "Study"

Plunger:
  type: Tool
  description: "The good-ole-fashioned plunger. Perfect for solving your porcelain problems."
  use:
    text: "You manage to unclog the toilet, and found the key to the greenhouse was causing the clog!"
    action: "use"
  pair: "Toilet"

Broom:
  type: Tool
  description: "Perfect for those dusty floors"
  use:
    text: "You sweep the floors a bit. I guess it's lest dusty now..."
    action: "use"
  pair: null

Bucket:
  type: Tool
  description: "A bucket. Nothing more, nothing less."
  use:
    text: "You put the bucket on your head. A small (but false) sense of safety comforts you!"
    action: "use"
  pair: null

Book of Foods:
  type: Book
  description: "A book of recipes. How handy!"
  use:
    text: "While flipping through the book, you see the page marked Pizza starred. How strange..."
    action: "read"
  tip: "Pizza is a favorite."

Wildlife Journal:
  type: Book
  description: "A peer reviewed journal of the various wildlife found in North America."
  use:
    text: "The various pictures and fun facts are highly interesting. When you flip to the page about frogs, a hand-drawn picture of one falls out signed The Warden"
    action: "read"
  tip: "The Warden likes frogs."

Greenhouse Catalogue:
  type: Book
  description: "A catalogue of the many different types of plants found in the Greenhouse."
  use:
    text: "You're surprised to learn how many plants there are in the Greenhouse! You find the chapter on flowers was highlighted in the table of contents."
    action: "read"
  tip: "The chapter on flowers was highlighted."

Toilet:
  type: Tool
  description: "A toilet you ripped from the wall of the bathroom. Somehow magically, it still works!"
  use:
    text: "You flush the toilet, but discover that it's clogged. If only you had a plunger..."
    action: "use"
  pair: null

Green Frog:
  type: Animal
  description: "A speckled green frog, found hopping around the courtyard."
  use:
    text: "The frog ribbits and seems a little annoyed that you pet it, but you wore gloves to make sure you didn't hurt it!"
    action: "pet"
  color: "Green"

Brown Frog:
  type: Animal
  description: "A plain brown frog. It wasn't too happy about being caught."
  use:
    text: "The frog seemed indifferent to being pet, but at least it made you quite happy!"
    action: "pet"
  color: "Brown"

Rose:
  type: Plant
  description: "A beautiful red rose."
  use:
    text: "Careful not to prick yourself on a thorn, you take a deep whiff of the flower. It smells delightful!"
    action: "observe"
  plantType: "Flower"

Frozen Pizza:
  type: Food
  description: "A frozen pizza, of the veggie variety."
  use:
    text: "You think about eating the frozen pizza, but you decide not to because you're not a psycho."
    action: "eat"
  flavor: null
  foodType: null
  hot: false

Dictionary:
  type: Book
  description: "A regular old dictionary."
  use:
    text: "You go to read the dictionary like a novel, but find it quite boring. At least you know a few more words now."
    action: "read"
  tip: null

Snail:
  type: Animal
  descriptin: "A very small, but very cute snail."
  use:
    text: "You run your hands along the shy snail's shell, and feel a bit better about the world"
    action: "pet"
  color: "Brown"

Tabby Cat:
  type: Animal
  description: "A cute, cuddly, warm tabby cat who's more than happy to join you on your adventure."
  use:
    text: "As you pet the cat, it begins to pur. And with each pur, you feel anxiety after another melt away."
    action: "pet"
  color: "Grey"

Four Leaf Clover:
  type: Plant
  description: "A green four leaf clover. How lucky!"
  use:
    text: "You observe the four leaf clover, and appreciate the simple beauty in this lucky item."
    action: "observe"
  plantType: "Clover"

Goldfish:
  type: Animal
  description: "A goldfish in a fishbowl."
  use:
    text: "You think about trying to pet the goldfish directly, but decide not to. Instead, you rub your hands along the bowl instead."
    action: "pet"
  color: "Orange"

Star Wars:
  type: Book
  description: "One of the Star Wars books. Specifically, Volume IV: A New Hope"
  use:
    text: "You sit down for a few hours and read some. While not particularly helpful for your journey, it felt good to relax for a while!"
    action: "read"
  tip: null

Oven Instruction Manual:
  type: Book
  description: "An instruction manual for an oven. You wonder if one can be found in this facility..."
  use:
    text: "A quick glance over of the manual doesn't reveal too much, but you learn that this type of oven has a pizza-reheat button!"
    action: "read"
  tip: "Frozen pizza can be reheated in the oven."

Veggie Pizza:
  type: Food
  description: "Fresh hot veggie pizza! It looks and smells delicious..."
  use:
    text: "You blow on the pizza to cool it a bit, and take a bite. The delicious flavors fill your mouth!"
    action: "eat"
  flavor: "savory"
  foodType: "eat"
  hot: true

Oven:
  type: Tool
  description: "An oven you ripped from the wall... and it still works?!"
  use:
    text: "You pop the frozen pizza in the oven, and let it cook! You have no idea how it's working with no electricity or gas, but you've seen weirder today."
    action: "use"
  pair: "Frozen Pizza"

Rat:
  type: Animal
  description: "A rat you found scurrying in the kitchen. You wonder if putting it on your head will grant you top tier cooking skills."
  use:
    text: "While skeptical at first, you reach to pet the rat. It's suprisingly soft!"
    action: "pet"
  color: "Gray"

Penguin:
  type: Animal
  description: "A cute penguin. No wonder you'd find it in the freezer!"
  use:
    text: "You've never pet a penguin before, so you were excited for the oppurtunity! Although to be honest, it wasn't all too different from what you'd expect."
    action: "pet"
  color: "Black and White"

Butterfly:
  type: Animal
  description: A beautiful butterfly, fragile and gentle!
  use:
    text: "You don't really know how to pet a butterfly without hurting it, so you let simply sit on you. How beautiful!"
    action: "pet"
  color: "Blue"


