scorpion:
  type: [Animal]
  description: "A venomous scorpion..."
  use:
    text: "The scorpion arches its tail..."
    action: "attack"
  min-damage: 3
  max-damage: 7

key:
  type: [Key]
  description: "An ancient key..."
  use:
    text: "The key feels heavy in your hand."

excalibur:
  type: [Weapon]
  description: "Ye sword of olde"
  use:
    text: "You slash with the sword."
    action: "null"
  min-damage: 1
  max-damage: 10

sand:
  type: [Item]
  description: "A million golden pieces of sand..."
  use:
    text: "You throw the sand. It gets in your eyes..."

lighter:
  type: [Item]
  description: "A small metal lighter..."
  use:
    text: "The lighter flickers to life..."
    action: "ignite"

coconut tree:
  type: [Plant]
  description: "A tall tree bearing coconuts."
  use:
    text: "You try to shake the tree, but nothing falls."
    action: "null"
  health: 10

coconut:
  type: [Healing]
  description: "A fresh coconut, brimming with hydrating juice."
  use:
    text: "You drink the coconut water."
    action: "heal"
  heal: 5

spring:
  type: [Stationary]
  description: "A bubbling natural spring..."
  use:
    text: "You take a sip from the spring and feel refreshed."
    action: "heal"

strange statue:
  type: [Stationary]
  description: "A weathered stone statue..."
  use:
    text: "The statue stands silently."
    action: "null"

haunted statue:
  type: [Stationary]
  description: "A statue transformed by flame..."
  use:
    text: "The statue crackles with energy..."
    action: "null"

unlit brazier:
  type: [Stationary]
  description: "A large metal brazier, filled with ash but unlit."
  use:
    text: "The lighter flickers..."
    action: "null"

lit brazier:
  type: [Stationary]
  description: "A brazier blazing with warmth..."
  use:
    text: "The brazier crackles..."

hidden symbols:
  type: [Stationary]
  description: "Mysterious symbols carved..."
  use:
    text: "You trace the symbols..."
    action: "inspect"

unlit torch:
  type: [Item]
  description: "A wooden torch, unlit..."
  use:
    text: "You hold the unlit torch."
    action: "light"

lit torch:
  type: [Item]
  description: "A torch that has been ignited..."
  use:
    text: "The lit torch crackles softly..."
    action: "light"

ancient scroll:
  type: [Item] # could be Magical if we define Magical
  description: "A fragile parchment..."
  use:
    text: "The scroll reads: 'Upon the cavern's faint glyphs, cast desert's grains to reveal your path. Quench the flame in pure waters to lift the veil.'"
    action: "read"

treasure chest:
  type: [Stationary]
  description: "A locked chest..."
  use:
    text: "You try to open the chest, but it remains locked."
    action: "null"
