excalibur:
  type: [Weapon]
  description: "Ye sword of olde"
  use:
      text: "You slash with the sword."
      action: "null"
  min-damage: 1
  max-damage: 10

copper sword:
  type: [Weapon]
  description: "An old copper sword"
  use:
      text: "You slash with the sword."
      action: "null"
  min-damage: 1
  max-damage: 4

poison frog:
  type: [Weapon, Animal]
  description: "A bright purple frog, oozing a thick liquid"
  use:
      text: "You place the frog gently on the floor. The frog croaks contentedly."
      action: "drop"
  min-damage: 2
  max-damage: 4

broom:
  type: [Item]
  description: "It's for sweeping."
  use:
      text: "The floor looks slightly less dusty."
      action: "null"

empty bucket:
  type: [Item]
  description: "It's full of air."
  use:
      text: "You approch the pond and fill the bucket with\u001B[34m water\u001B[0m."
      action: "fill"

full bucket:
  type: [Item]
  description: "It's full of water."
  use:
      text: "You empty the bucket out onto your target."
      action: "splash"

mop:
  type: [Item]
  description: "It's for mopping."
  use:
      text: "The floor looks slightly more damp."
      action: "null"

poster:
  type: [Item]
  description: "A classic."
  use:
      text: "What are you going to do with a poster?"
      action: "null"

book:
  type: [Item]
  description: "An old book about Java. It seems to have some purple residue on it."
  use:
      text: "You place the book gently on the floor."
      action: "drop"

blue key:
  type: [Item]
  description: "An worn key with A blue gem embedded within it's head."
  use:
      text: "You place and turn the \u001B[34mblue key\u001B[0m within it's keyhole."
      action: "unlock"

green key:
  type: [Item]
  description: "An worn key with A green gem embedded within it's head."
  use:
      text: "You place and turn the \u001B[32mgreen key\u001B[0m within it's keyhole."
      action: "unlock"

red key:
  type: [Item]
  description: "An worn key with A red gem embedded within it's head."
  use:
      text: "You place and turn the \u001B[31mred key\u001B[0m within it's keyhole."
      action: "unlock"
