excalibur:
  type: [Weapon]
  description: "Ye sword of olde"
  use:
      text: "You slash with the sword."
      action: "null"
  min-damage: 1
  max-damage: 10
poison frog:
  type: [Weapon, Animal]
  description: "A bright purple frog, oozing a thick liquid"
  use:
      text: "You place the frog gently on the floor. The frog croaks contentedly."
      action: "drop"
  min-damage: 2
  max-damage: 4
broom:
  type: [Item]
  description: "It's for sweeping."
  use:
      text: "The floor looks slightly less dusty."
      action: "null"
bucket:
  type: [Item]
  description: "It's empty."
  use:
      text: "You put the bucket on your head. You feel marginally safer."
      action: "null"
mop:
  type: [Item]
  description: "It's for mopping."
  use:
      text: "The floor looks slightly more damp."
      action: "null"
poster:
  type: [Item]
  description: "A classic."
  use:
      text: "What are you going to do with a poster?"
      action: "null"
book:
  type: [Item]
  description: "An old book about Java. It seems to have some purple residue on it."
  use:
      text: "You place the book gently on the floor."
      action: "drop"
      #senzu bean

bean:
  type: [Item]
  description: "an assuming oval shaped bean, its warm to the touch and you supspect it will taste gross."
  use:
    text: "you pop this warmish green bean in your mouth. it taste like kitty litter but you can feel your body and mind reinvoragated."
    action: "eat"
Unnamed Kid:
  type: [NPC]
  description: """
              in the center of the small courtayrd paved with grey bricks in an almost perfect fashion.
              we see a small boy with an orange gi on weirdly light blue boots and a small almost monkey like tail
              coming out of his backside. even though  he seems like a kid but he practicing martial arts with no one around
              """
  use:
    talk: "Hi my name is Goku, Usually I have my power pole when im traing so I look kinda weird "


          "if you see it around here can you drop it for me i can give you a pretty cool power up if you do "
    action:

  