poison frog:
  type: [Weapon, Animal]
  description: "A bright purple frog, oozing a thick liquid"
  use:
      text: "You place the frog gently on the floor. The frog croaks contentedly."
      action: "drop"
  min-damage: 2
  max-damage: 4
broom:
  type: [CleaningItem]
  description: "It's for sweeping."
  use:
      text: "The floor looks slightly less dusty."
      action: "sweep"
bucket:
  type: [CleaningItem]
  description: "It's empty."
  use:
      text: "You put the bucket on your head. You feel marginally safer."
      action: "wear"
mop:
  type: [CleaningItem]
  description: "It's for mopping."
  use:
      text: "The floor looks slightly more damp."
      action: "mop"
poster:
  type: [PrintMaterial]
  description: "A classic."
  use:
      text: "You put a poster of an old wizard on the wall."
      action: "place"
book:
  type: [PrintMaterial]
  description: "An old book about Java. It seems to have some purple residue on it."
  use:
      text: "You place the book gently on the floor."
      action: "drop"
gold key:
   type: [Weapon, Key]
   description: "A gold skeleton key."
   use:
       text: "You turn the key in the lock. It unlocks the door."
       action: "unlock"
   color: "gold"
   min-damage: 1
   max-damage: 3
excalibur:
  type: [Weapon]
  description: "Ye sword of olde"
  use:
      text: "You slash with the sword."
      action: "stab"
  min-damage: 1
  max-damage: 10
silver key:
   type: [Weapon, Key]
   description: "A silver skeleton key."
   use:
       text: "You turn the key in the lock. It unlocks the door."
       action: "unlock"
   color: "silver"
   min-damage: 1
   max-damage: 3