excalibur:
  type: [Weapon]
  description: "Ye sword of olde"
  use:
      text: "You slash with the sword."
      action: "null"
  min-damage: 1
  max-damage: 10
poison frog:
  type: [Weapon, Animal]
  description: "A bright purple frog, oozing a thick liquid"
  use:
      text: "You place the frog gently on the floor. The frog croaks contentedly."
      action: "drop"
  min-damage: 2
  max-damage: 4
broom:
  type: [Item]
  description: "It's for sweeping."
  use:
      text: "The floor looks slightly less dusty."
      action: "null"
bucket:
  type: [Item]
  description: "It's empty."
  use:
      text: "You put the bucket on your head. You feel marginally safer."
      action: "null"
mop:
  type: [Item]
  description: "It's for mopping."
  use:
      text: "The floor looks slightly more damp."
      action: "null"
poster:
  type: [Item]
  description: "A classic."
  use:
      text: "What are you going to do with a poster?"
      action: "null"
book:
  type: [Item]
  description: "An old book about Java. It seems to have some purple residue on it."
  use:
      text: "You place the book gently on the floor."
      action: "drop"
motorcycle:
  type: [Vehicle]
  description: "Rusty old motorcycle that goes super duper fast."
  use:
      text: "You get on the motorcycle but theres no gas."
      action: "null"
lamborghini:
  type: [Vehicle]
  description: "Matte Black Lamborghini SVJ glistens in the Garage light."
  use:
      text: "null"
      action: "unlock"
car keys:
  type: [Key]
  description: "Lamborghini car keys."
  use:
      text: "Black car keys that jingle."
      action: "open car door"
enderflame:
  type: [Weapon]
  description: "This glowing purple enderflame staff that contains extreme aura."
  use:
      text: "You grab the enderflame and power and great energy surfe through you."
      action: "equip"
  min-damage: 20
  max-damage: 40
steve:
  type: [Enemy]
  description: "Steve from minecraft has super cool armor shields on his body ready to battle you."
  use:
      text: "You are dead."
      action: "kill"
  min-damage: 30
  max-damage: 50
  health: 200