"Starting Room":
  contents: [poison frog]
  doors:
      green: "Closet"
      blue: "Green Room"
      brown: "Basement"
  lockedDoors:
      brown: "brown key"

"Closet":
  contents: [broom, mop, bucket, poster, brown key]
  doors:
      green: "Starting Room"
  lockedDoors: {}

"Basement":
  contents: [crystal ball, shield, map, rat, dagger]
  doors:
      brown: "Starting Room"
  lockedDoors: {}
      
"Green Room":
  contents: [carnivorous plant, medicinal herbs, mysterious seeds]
  doors:
      blue: "Starting Room"
  lockedDoors : {}
