"Unending Desert":
  contents: [scorpion, sand, lighter, cactus]
  doors:
    blue: "Oasis"
    red: "Red Rock Cavern"

"Oasis":
  contents: [coconut tree, spring, strange statue, unlit brazier]
  doors:
    blue: "Unending Desert"

"Red Rock Cavern":
  contents: [unlit torch, unintelligible symbols, glowvine]
  doors:
    red: "Unending Desert"
    black: "Hidden Chamber"

"Hidden Chamber":
  contents: [ancient scroll, axe]
  doors:
    black: "Red Rock Cavern"

"Veiled Passage":
  contents: []
  doors:
    green: "Oasis"
