"Unending Desert":
  contents: [scorpion, sand, lighter]
  doors:
    blue: "Oasis"
    red: "Red Rock Cavern"

"Oasis":
  contents: [coconut tree, spring, strange statue, unlit brazier]
  doors:
    blue: "Unending Desert"
    green: "Veiled Passage"

"Red Rock Cavern":
  contents: [unlit torch, hidden symbols]
  doors:
    red: "Unending Desert"
    black: "Hidden Chamber"

"Hidden Chamber":
  contents: [ancient scroll, treasure chest]
  doors:
    white: "Red Rock Cavern"

"Veiled Passage":
  contents: []
  doors:
    green: "Oasis"
