"Unending Desert":
  contents: [scorpion, sand, lighter]
  doors:
      blue: "Oasis"
      red: "Red Rock Cavern"

"Oasis":
  contents: [coconut tree, spring, statue, unlit brazier]
  doors:
      blue: "Unending Desert"
      green: "Paradise"

"Red Rock Cavern":
  contents: [hidden symbols, unlit torch, minecart]
  doors:
      red: "Unending Desert"
      black: "Hidden Study"

"Hidden Study":
  contents: [ancient scroll, treasure chest]
  doors:
      black: "Red Rock Cavern"

