"Starting Room":
  contents: [poison frog]
  doors:
      green: "Garden"
      red: "Forge"
      blue: "Pond"
      white: "Bright Room"

"Closet":
  contents: [broom, mop, poster]
  doors:
      green: "Starting Room"

"Garden":
  contents: [Green Key]
  doors:
      green: "Starting Room"

"Pond":
  contents: [Blue Key]
  doors:
    blue: "Starting Room"

"Forge":
  contents: [Red Key]
  doors:
    red: "Starting Room"

"Bright Room":
  contents: [excalibur]
  doors:
    white: "Starting Room"
    black: "Boss Room"

"Boss Room":
  contents: []
  doors:
    black: "Starting Room"