"Starting Room":
  contents: [poison frog, mushroom]
  doors:
      blue: "Storage Room"
"Closet":
  contents: [broom, bucket, key]
  doors:
      blue: "Storage Room"
"Storage Room":
  contents: [poster, cactus]
  doors:
    yellow: "Closet"
    green: "Starting Room"
    orange: "Display Case"
    red: "Mysterious Room"
"Display Case":
  contents: [sunflower]
  doors:
    blue: "Storage Room"

"Mysterious Room":
  contents: [ancient sword]
  doors:
    blue: "Storage Room"

