"Starting Room":
  contents: [poison frog, purple potion]
  doors:
      green: "Closet"
      white: "Side Room"
      gold: 
        room: "Final Room"
        locked: true
      
"Closet":
  contents: [mop, bucket, poster, broom, gold potion]
  doors:
      green: "Starting Room"
"Side Room":
  contents: [herbs, key, sword, black potion]
  doors:
    white: "Starting Room"
"Final Room":
  contents: [healing stone]
  doors:
    gold: "Starting Room"
  enemy:
    health: 20