"library":
  contents: [book, cactus, sunflower, tulip]
  doors:
      closet: "closet"
"closet":
  contents: [broom, mop]
  doors:
      library: "library"
      left tunnel: "left tunnel"
      right tunnel: "right tunnel"
"left tunnel":
  contents: [sword]
  doors:
      closet: "closet"
      vault: "vault"
      skeleton: "skeleton"
"skeleton":
  contents: [redkey]
  doors:
    left tunnel: "left tunnel"
"vault":
  contents: [greenkey]
  doors:
    left tunnel: "left tunnel"
"right tunnel":
  contents: [rock, mouse]
  doors:
    closet: "closet"
    gold door: "gold door"
"gold door":
  contents: []
  doors: 
    right tunnel: "right tunnel"
"light":
  contents: []
  doors:




  
  

