"Starting Room":
  contents: [poison frog, rusty key]
  doors:
      green: "Closet"
      red: "Attic"
"Closet":
  contents: [broom, mop, bucket, poster, toy chest]
  doors:
      green: "Starting Room"
"Attic":
  contents: [treasure chest]
  doors:
      red: "Starting Room"
      portal: "Dungeon"
"Dungeon":
  contents: [skeleton warrior]
  doors:
      portal: "Attic"
