excalibur:
  name: "Excalibur"
  type: weapon
  description: "Ye sword of olde"
  min-damage: 1
  max-damage: 10


poisonFrog:
  name: "Poisonous Frog"
  type: [weapon, animal]
  description: "A bright purple frog, oozing a thick liquid"
  min-damage: 2
  max-damage: 4